/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SmartCast;

import esprit.smartcast.controller.HomeController;
import io.datafx.controller.flow.Flow;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

	public static void main(String[] args) {
		launch(args);
	}
	 @Override
    public void start(Stage primaryStage) throws Exception {
        new Flow(HomeController.class).startInStage(primaryStage);
    }
}

