/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SmartCast;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

	public static void main(String[] args) {
		launch(args);
	}
	@Override
	public void start(Stage primaryStage) throws Exception {
		StackPane pane = new StackPane();
		Scene scene = new Scene(pane);
		primaryStage.setTitle("Hello App");
		primaryStage.setScene(scene);
		primaryStage.show();
	}

}
